export const AG_GRID_KEY =
  'Using_this_AG_Grid_Enterprise_key_( AG-037106 )_in_excess_of_the_licence_granted_is_not_permitted___Please_report_misuse_to_( legal@ag-grid.com )___For_help_with_changing_this_key_please_contact_( info@ag-grid.com )___( RelationalAI )_is_granted_a_( Multiple Applications )_Developer_License_for_( 5 )_Front-End_JavaScript_developers___All_Front-End_JavaScript_developers_need_to_be_licensed_in_addition_to_the_ones_working_with_AG_Grid_Enterprise___This_key_has_been_granted_a_Deployment_License_Add-on_for_( 2 )_Production_Environments___This_key_works_with_AG_Grid_Enterprise_versions_released_before_( 23 March 2024 )____[v2]_MTcxMTE1MjAwMDAwMA==8395915de634959e5acb2eddbd75e4a9';

export const PAGE_TITLE_SUFFIX = '| Relational AI Console';
